version: "2"
services:
  gateway:
    build: nginx
    volumes:
      - ./data/log/nginx:/var/log/nginx/
      - ./data/log/humhub:/var/www/concamin/logs
      - ./concamin:/var/www/concamin
    ports:
      - "80:80"
    tty: true
    links:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: pass1word
       MYSQL_DATABASE: humhub
       MYSQL_USER: humhub
       MYSQL_PASSWORD: humhub
